### PR TITLE
Fix #180: Document specific errors in REST API responses

### LINKED ISSUE #180: Document specific errors in REST API responses
Analyze code and add individual errors for cases when REST API calls fail.

### PR DESCRIPTION
**Pull request by romanstrobl**

### CODE REVIEW

File: user-data-store-server/src/main/java/com/wultra/security/userdatastore/service/PhotoService.java [hunk 1]
```diff
@@ -65,7 +64,7 @@ public PhotoResponse fetchPhotos(final String userId, final Optional<String> doc
         if (documentId.isPresent()) {
             final Optional<DocumentEntity> documentEntityOptional = documentRepository.findById(documentId.get());
             if (documentEntityOptional.isEmpty()) {
-                return new PhotoResponse(Collections.emptyList());
+                throw new ResourceNotFoundException("Document not found, ID: '%s'".formatted(documentId));
```
Comment (banterCZ) [inline user-data-store-server/src/main/java/com/wultra/security/userdatastore/service/PhotoService.java:67]: dtto

**Review by banterCZ — APPROVED** [review]
Looks good.
